import { Poppins } from "next/font/google";
import "./globals.css";
import 'reactjs-popup/dist/index.css';
import "react-toastify/dist/ReactToastify.css";
import Navigation from "@/components/navigation";
import Mates from "@/components/mates";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  // preload: false
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navigation />
        <Mates>
          <div className="pt-10 px-8">{children}</div>
        </Mates>
      </body>
    </html>
  );
}
